"""
scrapers/chains.py - Returns hardcoded demo jobs for major chains.
Web scraping of chain career pages is unreliable on free hosting
(JS-rendered pages, bot detection). Real jobs come from Adzuna/JSearch APIs.
This file provides reliable fallback data for the chains.
"""
import logging
log = logging.getLogger("scraper.chains")

CHAIN_JOBS = [
    {"title":"Crew Member","company":"McDonald's","city":"Dresden","district":"Dresden Mitte","type":"Minijob","timing":"Sofort","category":"🍔 Food","description":"Join our team at McDonald's Dresden. No experience needed. Flexible hours available.","url":"https://jobs.mcdonalds.de","via":"mcdonalds.de","is_new":True,"source":"chains"},
    {"title":"Crew Member","company":"McDonald's","city":"Leipzig","district":"Leipzig Mitte","type":"Minijob","timing":"Sofort","category":"🍔 Food","description":"Join our team at McDonald's Leipzig. No experience needed. Flexible hours available.","url":"https://jobs.mcdonalds.de","via":"mcdonalds.de","is_new":True,"source":"chains"},
    {"title":"Kassierer/in","company":"REWE","city":"Dresden","district":"Dresden","type":"Minijob","timing":"Flexible","category":"🛒 Retail","description":"Checkout and customer service at REWE Dresden. Part-time and mini-job positions available.","url":"https://karriere.rewe.de","via":"rewe-group.com","is_new":False,"source":"chains"},
    {"title":"Kassierer/in","company":"REWE","city":"Leipzig","district":"Leipzig","type":"Minijob","timing":"Flexible","category":"🛒 Retail","description":"Checkout and customer service at REWE Leipzig.","url":"https://karriere.rewe.de","via":"rewe-group.com","is_new":False,"source":"chains"},
    {"title":"Regalmitarbeiter/in","company":"Lidl","city":"Dresden","district":"Dresden","type":"Minijob","timing":"Early mornings","category":"🛒 Retail","description":"Stock replenishment and shelf management at Lidl Dresden.","url":"https://jobs.lidl.de","via":"lidl.de","is_new":False,"source":"chains"},
    {"title":"Regalmitarbeiter/in","company":"Lidl","city":"Chemnitz","district":"Chemnitz","type":"Minijob","timing":"Early mornings","category":"🛒 Retail","description":"Stock replenishment at Lidl Chemnitz.","url":"https://jobs.lidl.de","via":"lidl.de","is_new":True,"source":"chains"},
    {"title":"Warehouse Assistant","company":"Amazon","city":"Leipzig","district":"Leipzig Süd","type":"Teilzeit","timing":"Weekends","category":"📦 Warehouse","description":"Picking, packing and sorting at Amazon Leipzig fulfillment center.","url":"https://amazon.jobs","via":"amazon.jobs","is_new":True,"source":"chains"},
    {"title":"Paketzusteller/in","company":"DHL","city":"Dresden","district":"Dresden","type":"Nebenjob","timing":"Mornings","category":"📦 Warehouse","description":"Package delivery in Dresden area. Driving licence required.","url":"https://careers.dhl.com","via":"careers.dhl.com","is_new":True,"source":"chains"},
    {"title":"Paketzusteller/in","company":"DHL","city":"Leipzig","district":"Leipzig","type":"Nebenjob","timing":"Mornings","category":"📦 Warehouse","description":"Package delivery in Leipzig area.","url":"https://careers.dhl.com","via":"careers.dhl.com","is_new":False,"source":"chains"},
    {"title":"Barista","company":"Starbucks","city":"Dresden","district":"Dresden Mitte","type":"Werkstudent","timing":"Flexible","category":"🍔 Food","description":"Coffee preparation and customer service at Starbucks Dresden.","url":"https://starbucks.com/careers","via":"starbucks.com","is_new":True,"source":"chains"},
    {"title":"Verkäufer/in","company":"DM Drogerie","city":"Leipzig","district":"Leipzig","type":"Minijob","timing":"Flexible","category":"💊 Healthcare","description":"Customer service and shelf management at DM Leipzig.","url":"https://www.dm.de/unternehmen/karriere","via":"dm.de","is_new":False,"source":"chains"},
    {"title":"Verkäufer/in","company":"DM Drogerie","city":"Dresden","district":"Dresden","type":"Minijob","timing":"Flexible","category":"💊 Healthcare","description":"Customer service at DM Dresden.","url":"https://www.dm.de/unternehmen/karriere","via":"dm.de","is_new":False,"source":"chains"},
    {"title":"Aushilfe Lager","company":"Hermes","city":"Leipzig","district":"Leipzig","type":"Minijob","timing":"Evenings","category":"📦 Warehouse","description":"Parcel sorting at Hermes Leipzig depot. Evening shifts available.","url":"https://karriere.hermesworld.com","via":"hermesworld.com","is_new":True,"source":"chains"},
    {"title":"Delivery Rider","company":"Lieferando","city":"Dresden","district":"Dresden","type":"Nebenjob","timing":"Evenings/Weekends","category":"🚗 Delivery","description":"Food delivery by bike or scooter in Dresden. Flexible hours.","url":"https://lieferando.de/jobs","via":"lieferando.de","is_new":True,"source":"chains"},
    {"title":"Delivery Rider","company":"Lieferando","city":"Leipzig","district":"Leipzig","type":"Nebenjob","timing":"Evenings/Weekends","category":"🚗 Delivery","description":"Food delivery by bike or scooter in Leipzig.","url":"https://lieferando.de/jobs","via":"lieferando.de","is_new":False,"source":"chains"},
    {"title":"Rezeptionist/in","company":"Ibis Hotel","city":"Dresden","district":"Dresden","type":"Teilzeit","timing":"Mornings/Evenings","category":"🏨 Hotel","description":"Front desk and guest services at Ibis Hotel Dresden.","url":"https://careers.accor.com","via":"ibis.com","is_new":False,"source":"chains"},
    {"title":"Haushaltshelfer/in","company":"Motel One","city":"Leipzig","district":"Leipzig","type":"Minijob","timing":"Mornings","category":"🏨 Hotel","description":"Room cleaning and housekeeping at Motel One Leipzig.","url":"https://www.motel-one.com/de/jobs","via":"motel-one.com","is_new":True,"source":"chains"},
    {"title":"Verkäufer/in","company":"H&M","city":"Dresden","district":"Dresden Centrum","type":"Minijob","timing":"Weekends","category":"🛒 Retail","description":"Sales and customer service at H&M Dresden.","url":"https://career.hm.com","via":"hm.com","is_new":False,"source":"chains"},
    {"title":"Küchenhelfer/in","company":"Burger King","city":"Chemnitz","district":"Chemnitz","type":"Minijob","timing":"Evenings","category":"🍔 Food","description":"Kitchen assistance at Burger King Chemnitz.","url":"https://www.burgerking.de/jobs","via":"burgerking.de","is_new":True,"source":"chains"},
    {"title":"Tankwart/in","company":"Aral","city":"Zwickau","district":"Zwickau","type":"Minijob","timing":"Weekends","category":"🏢 Other","description":"Customer service at Aral petrol station in Zwickau.","url":"https://www.aral.de/karriere","via":"aral.de","is_new":False,"source":"chains"},
    {"title":"Markthelfer/in","company":"OBI Baumarkt","city":"Görlitz","district":"Görlitz","type":"Minijob","timing":"Flexible","category":"🔧 Hardware","description":"Customer service and shelf stocking at OBI Görlitz.","url":"https://www.obi.de/unternehmen/karriere","via":"obi.de","is_new":True,"source":"chains"},
    {"title":"Fitnesstrainer/in","company":"McFit","city":"Leipzig","district":"Leipzig","type":"Werkstudent","timing":"Flexible","category":"🎬 Entertainment","description":"Coaching and customer support at McFit Leipzig.","url":"https://mcfit.com","via":"mcfit.com","is_new":False,"source":"chains"},
    {"title":"Kinomitarbeiter/in","company":"CinemaxX","city":"Dresden","district":"Dresden","type":"Nebenjob","timing":"Evenings/Weekends","category":"🎬 Entertainment","description":"Ticket sales and cinema operations at CinemaxX Dresden.","url":"https://cinemaxx.de","via":"cinemaxx.de","is_new":False,"source":"chains"},
    {"title":"Kassenmitarbeiter/in","company":"Aldi","city":"Freiberg","district":"Freiberg","type":"Minijob","timing":"Flexible","category":"🛒 Retail","description":"Checkout and customer service at Aldi Freiberg.","url":"https://www.aldi-sued.de/karriere","via":"aldi.de","is_new":True,"source":"chains"},
]

def fetch_chain_jobs():
    log.info(f"Chains: returning {len(CHAIN_JOBS)} hardcoded jobs")
    return CHAIN_JOBS
